#!/bin/bash

if [[ -e /Library/LaunchDaemons/dev.traurige.kayokod.plist ]]; then
    launchctl load -w /Library/LaunchDaemons/dev.traurige.kayokod.plist;
elif [[ -e /var/jb/Library/LaunchDaemons/dev.traurige.kayokod.plist ]]; then
    launchctl load -w /var/jb/Library/LaunchDaemons/dev.traurige.kayokod.plist;
fi
