name: Build Package

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions:
  contents: write

env:
  VERSION: 1.0
  FINALPACKAGE: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    name: Build (${{ matrix.build_variant }})
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_variant: legacy
            env_script: devkit/env.sh
          - build_variant: rootless
            env_script: devkit/rootless.sh
          - build_variant: roothide
            env_script: devkit/roothide.sh

    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        echo "$THEOS/bin" >> "$GITHUB_PATH"
        echo "THEOS=$THEOS" >> $GITHUB_ENV
        echo "THEOS_IGNORE_PARALLEL_BUILDING_NOTICE=yes" >> $HOME/.theosrc

    - name: Checkout Theos (RootHide)
      uses: actions/checkout@v4
      with:
        repository: roothide/theos
        ref: d4826f4e54127cfe1de88103b69b92107591c05b
        path: theos
        submodules: recursive

    - name: Install iOS SDK
      run: |
        cd "$THEOS"
        ./bin/install-sdk iPhoneOS16.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Theos dependencies
      run: |
        brew install ldid xz
        echo "$(brew --prefix)/bin" >> "$GITHUB_PATH"
        command -v ldid
        command -v xz

    - name: Build Package
      run: |
        source "${{ matrix.env_script }}"
        export THEOS="$GITHUB_WORKSPACE/theos"
        make package

    - name: Collect dSYMs
      run: |
        find .theos/obj -name "*.dSYM" -exec cp -r {} ./packages/ \;

    - name: Upload dSYMs
      uses: actions/upload-artifact@v4
      with:
        name: symbols-${{ matrix.build_variant }}
        path: |
          ./packages/*.dSYM
        if-no-files-found: warn

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ matrix.build_variant }}
        path: |
          ./packages/*.deb
        if-no-files-found: error

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract Version
      run: |
        VERSION=$(grep '^Version:' control | awk '{print $2}')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Download Packages
      uses: actions/download-artifact@v4
      with:
        pattern: packages-*
        path: release-packages
        merge-multiple: true

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}+Lessica
        draft: true
        prerelease: false
        files: |
          release-packages/*.deb
